
name: "bge_bls_model"
backend: "python"
max_batch_size: 128

input [
  {
    name: "input"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "dense_vecs"
    data_type: TYPE_FP32
    dims: [1024]
  },
  {
    name: "sparse_vecs"
    data_type: TYPE_STRING
    dims: [1]
  },
  {
    name: "dense_token_num"
    data_type: TYPE_UINT32
    dims: [1]
  },
  {
    name: "sparse_token_num"
    data_type: TYPE_UINT32
    dims: [1]
  }
]
